### PR TITLE
prep-css-flexbox - Patricia Manalang

### PR DESCRIPTION
**Pull request by patriciamanalang**
Screen Shot 2022-08-05 at 1 59 35 PM
Screen Shot 2022-08-05 at 3 01 51 PM
Screen Shot 2022-08-05 at 3 11 47 PM
Screen Shot 2022-08-05 at 3 16 55 PM

### CODE REVIEW

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Hi Patricia, try reworking your solutions to not modify the html. You can target elements with an id attributes using `#`, as in `#card-deck`

**Comment by patriciamanalang** [comment]
Screen Shot 2022-08-06 at 9 26 57 AM
Screen Shot 2022-08-06 at 9 35 28 AM
Screen Shot 2022-08-06 at 9 47 36 AM
Screen Shot 2022-08-06 at 9 50 42 AM

**Comment by patriciamanalang** [comment]
Screen Shot 2022-08-06 at 9 26 57 AM
Screen Shot 2022-08-06 at 9 35 28 AM
Screen Shot 2022-08-06 at 9 47 36 AM
Screen Shot 2022-08-06 at 9 50 42 AM

**Comment by patriciamanalang** [comment]
Screen Shot 2022-08-06 at 9 26 57 AM
Screen Shot 2022-08-06 at 9 35 28 AM
Screen Shot 2022-08-06 at 9 47 36 AM
Screen Shot 2022-08-06 at 9 50 42 AM

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
